# .github/workflows/init.yml
name: Initialize Template

#
# Run this on creation of a branch or ref
#
on:
  push:
    branches: main

jobs:
  build:
    #
    # Change this to make sure your workflow doesn't initialize on your template!
    #
    if: github.repository != 'nFinus/template-init-test'

    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      #
      # Check if there is a template recipe
      #
      - id: template_exists
        name: Check template
        uses: andstor/file-existence-action@v1
        with:
          files: .tmplr.yml

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: Install jq
        id: install-jq
        shell: bash
        run: |
          mkdir -p ${HOME}/.local/bin
          wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O ${HOME}/.local/bin/jq
          chmod +x ${HOME}/.local/bin/jq
          echo "::set-output name=jq-binary::${HOME}/.local/bin/jq"

      - name: Get repo description
        run: |
          echo 'repo_description<<EOF' >> $GITHUB_ENV
          curl -s https://api.github.com/repos/${{ github.repository }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          | jq -r '.description' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - run: echo "${{ env.repo_description }}"
      #
      # Run tmplr with required environment variables,
      # and remove the template recipe afterwards.
      #
      # Use this to get all the values you want from GitHub Action contexts
      # and set them as environment variables for tmplr.
      
      - name: Apply template
        if: steps.template_exists.outputs.files_exists == 'true'
        run: npx tmplr && rm -fr .tmplr.yml && rm -fr .github/workflows/init.yml
        env:
          owner_name: ${{ github.event.repository.owner.name }}
          owner_email: ${{ github.event.repository.owner.email }}
          repo_name: ${{ github.event.repository.name }}
          repo_url: ${{ github.event.repository.ssh_url }}
          repo_path: ${{ github.repository }}
          repo_description: ${{ env.repo_description }}

      #
      # Commit the code
      #
      - name: Git Commit/Push Changes
        uses: actions-x/commit@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Initialized template.'