
name: Initialize Template

on:
  push:
    branches:
      - main

jobs:
  precheck:
    # Critical step, this ensures this workflow doesn't run after the first commit
    if: github.event.head_commit.message == "Initial commit"
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.runonce_exists.outputs.files_exists }}
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - name: Check out Git repository
        uses: actions/checkout@v2

      # Check if the setup script still exists. if it doesn't,
      # this workflow should do nothing.
      - id: runonce_exists
        name: Check if runonce script exists
        uses: andstor/file-existence-action@v1
        with:
          files: scripts/init/runOnce.sh

  template:
    needs: precheck
    if: ${{ needs.precheck.outputs.exists == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: Install jq
        id: install-jq
        shell: bash
        run: |
          mkdir -p ${HOME}/.local/bin
          wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O ${HOME}/.local/bin/jq
          chmod +x ${HOME}/.local/bin/jq
          echo "::set-output name=jq-binary::${HOME}/.local/bin/jq"

      - name: Fetch the repo description from github api
        run: |
          echo 'repo_description<<EOF' >> $GITHUB_ENV
          curl -s https://api.github.com/repos/${{ github.repository }} \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            | jq -r '.description' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Run the init script to replace repo name and description
        env:
          repo_name: ${{ github.event.repository.name }}
          repo_description: ${{ env.repo_description }}
        run: exec ${{ github.workspace }}/scripts/init/runOnce.sh

      - name: Delete Template Readme
        run: rm ${{ github.workspace }}/README.md

      - name: Delete the script.
        run: rm ${{ github.workspace }}/scripts/init/runOnce.sh

      - name: Git Commit/Push Changes
        uses: actions-x/commit@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Initialized template [skip-ci]'